95 Fix room bug
dorm-social-room-manager/dsrm-backend pull request #100
Opened 2023-06-03 12:33 UTC by Adrian-Rochminski

2023-06-03 17:03 UTC, Krizzuu requested changes
I think you there should be added keyOwner in RoomRequestDTO as task specified
"In POST /admin/rooms in body add keyOwner attribute of string which is related user id..."

2023-06-04 19:25 UTC, Krizzuu approved these changes, later dismissed
looks ok

2023-06-05 20:43 UTC, HerbMat requested changes

2023-06-05 20:43 UTC, HerbMat commented on src/main/java/com/dsrm/dsrmbackend/mappers/RoomMapper.java
> +@Mapper(componentModel = "spring", uses = UserMapper.class)
Do not use it that way. Please use getReferenceById to set a User in room like with roomType

2023-06-06 21:50 UTC, HerbMat approved these changes

2023-06-06 21:50 UTC, merged