5 add entitites and repositories
dorm-social-room-manager/dsrm-backend pull request #20
Opened 2022-12-07 14:48 UTC by Adrian-Rochminski

2022-12-07 21:38 UTC, HerbMat requested changes

2022-12-07 21:38 UTC, HerbMat commented on src/main/java/com/dsrm/dsrmbackend/Controllers/UserController.java
> +    User addUser(@RequestBody UserDTO userDTO) {
it should be void instead of User

2022-12-07 21:38 UTC, HerbMat commented on src/main/java/com/dsrm/dsrmbackend/Controllers/UserController.java
> +        return userService.getUserMapper().toUser(userDTO);
But it should be void so make it just empty method.  But for future, never use run method that way. You are breaking encapsulation.

2022-12-07 21:38 UTC, HerbMat commented on src/main/java/com/dsrm/dsrmbackend/Controllers/UserController.java
> +    ResponseEntity<Object> oneUser(@PathVariable Long id) throws JSONException {
Why? Rename it to getUser and it should return entity/userDto object. But a little different than that used as request body in create user

2022-12-07 21:38 UTC, HerbMat commented on src/main/java/com/dsrm/dsrmbackend/Controllers/UserController.java
> +        return new ResponseEntity(outputObj,HttpStatus.OK);
for now return null;

2022-12-07 21:38 UTC, HerbMat commented on src/main/java/com/dsrm/dsrmbackend/Controllers/UserController.java
> +    public ResponseEntity readBooks (@RequestParam  Pageable pageable,@RequestParam Long pageNum) {
it should be ```ResponseEntity<Page<UserDto>> ```. By userdto I mean the same as object returned in endpoint above. ```pageNum``` is not necessery. You require Pageable which has page and pagenumber. And pageable does not need ```@RequestParam``` annotation

2022-12-07 21:38 UTC, HerbMat commented on src/main/java/com/dsrm/dsrmbackend/Controllers/UserController.java
> +        return ResponseEntity.ok(userService.readUsers(pageable));
for now return ```Page.empty()```

2022-12-07 21:38 UTC, HerbMat commented on src/main/java/com/dsrm/dsrmbackend/DTOobjects/UserDTO.java
> +public class UserDTO {
Rename to UserRequestDTO and UserDTO should be object returned in response.

2022-12-07 21:38 UTC, HerbMat commented on src/main/java/com/dsrm/dsrmbackend/DTOobjects/UserDTO.java
> +package com.dsrm.dsrmbackend.DTOobjects;
rename to dto . By oracle specification, packages should not have uppercased characters.

2022-12-07 21:38 UTC, HerbMat commented on src/main/java/com/dsrm/dsrmbackend/Controllers/UserController.java
> +package com.dsrm.dsrmbackend.Controllers;
rename to controllers . By oracle specification, packages should not have uppercased characters.

2022-12-07 21:38 UTC, HerbMat commented on src/main/java/com/dsrm/dsrmbackend/mappers/UserMapper.java
> +public class UserMapper {
For now remove this class. It would be not necessery, because we will be using mapstruct.

2022-12-07 21:38 UTC, HerbMat commented on src/main/java/com/dsrm/dsrmbackend/pageable/PaginatedUserResponse.java
> +public class PaginatedUserResponse {
It also won't be not necessary. We will be returning Spring Page object.

2022-12-07 21:38 UTC, HerbMat commented on src/main/java/com/dsrm/dsrmbackend/services/UserService.java
> +@Getter
Service should not have getters and setters. For this pull request this class won't be necessary remove. Or at least keep it empty.

2022-12-07 21:38 UTC, HerbMat commented on src/main/java/com/dsrm/dsrmbackend/tablesrepo/UserRepo.java
> +    Page<User> findAll(Pageable pageable);
this method is builtin inside ```JpaRepository``` you do not need to implement it by yourself.

2022-12-07 21:38 UTC, HerbMat commented on src/main/java/com/dsrm/dsrmbackend/tables/Reservation.java
> +package com.dsrm.dsrmbackend.tables;
it should be entity. https://stackoverflow.com/questions/29277399/differentiation-between-entity-and-table First answer explains difference

2022-12-07 21:38 UTC, HerbMat commented on src/main/java/com/dsrm/dsrmbackend/tablesrepo/ReservationRepo.java
> +package com.dsrm.dsrmbackend.tablesrepo;
just repositories in package name

2022-12-07 21:38 UTC, HerbMat commented on src/main/java/com/dsrm/dsrmbackend/tables/Reservation.java
> +    private Set<Room> room;
I made mistake it should ManyToOne. But it should be point to single room.

2022-12-07 21:38 UTC, HerbMat commented on src/main/java/com/dsrm/dsrmbackend/tables/Reservation.java
> +    private Set<User> user;
AS above

2022-12-07 21:38 UTC, HerbMat commented on src/main/java/com/dsrm/dsrmbackend/tables/Room.java
> +    private Set<RoomType> roomType;
As above it should be ManyToOne. I made mistake in description but it should point to single entity.

2022-12-07 21:38 UTC, HerbMat commented on src/main/java/com/dsrm/dsrmbackend/tables/Room.java
> +    @Column(name = "key_owner_id")
@Column is not necessary when you use @JoinColumn and as above I mentioned it should be other way ManyToOne here

2022-12-07 21:39 UTC, HerbMat commented
Poprawiłem opis taska. Ogólnie powinno być ManyToOne zamiast OneToMany bo chcemy mieć referencje do jednego elementu a nie wielu.

2022-12-08 21:24 UTC, Adrian-Rochminski commented
closes:  #5, #6, #7

2022-12-10 18:39 UTC, HerbMat requested changes

2022-12-10 18:39 UTC, HerbMat commented on src/main/java/com/dsrm/dsrmbackend/controllers/UserController.java
> +    @PostMapping(value = "/users", consumes ="application/json")
```MediaType.APPLICATION_JSON_VALUE``` And in all  endpoints instead of "application/json"

2022-12-10 18:39 UTC, HerbMat commented on src/main/java/com/dsrm/dsrmbackend/controllers/UserController.java
> +        JSONObject outputObj = new JSONObject();
remove this JsonObject. We will never use that.

2022-12-11 22:36 UTC, HerbMat approved these changes

2022-12-11 22:36 UTC, merged