23 create user service
dorm-social-room-manager/dsrm-backend pull request #38
Opened 2023-01-04 19:08 UTC by Adrian-Rochminski

Closes: #23

2023-01-07 09:08 UTC, HerbMat requested changes

2023-01-07 09:08 UTC, HerbMat commented on src/main/java/com/dsrm/dsrmbackend/controllers/UserController.java
> +        return ResponseEntity.of(Optional.of(user.map(userMapper::toUserDTO)));
```ResponseEntity.of(user.map(userMapper::toUserDTO));``` is enough

2023-01-07 09:08 UTC, HerbMat commented on src/main/java/com/dsrm/dsrmbackend/mappers/UserMapper.java
> +    List<Role> toListMap(List<Long> id);
This should be in rolemapper. And rename it to something meaningful like toRolesList. And this new mapper can be used by this by using ```@Mapper(componentModel = "spring", uses = RoleMapper.class)```

2023-01-07 09:08 UTC, HerbMat commented on src/main/java/com/dsrm/dsrmbackend/mappers/UserMapper.java
> +    Set<Role> toSetMap(List<Role> list);
As above

2023-01-07 09:08 UTC, HerbMat commented on src/main/java/com/dsrm/dsrmbackend/mappers/UserMapper.java
> +    Role toRoleMap(Long id);
Just to **toRole**

2023-01-07 09:08 UTC, HerbMat commented on src/main/resources/application-local.yml
> +    url: jdbc:mariadb://localhost:3306/TEST
do we need to change that?

2023-01-07 09:08 UTC, HerbMat commented on src/test/java/com/dsrm/dsrmbackend/UserControllerInitializer.java
> +public class UserControllerInitializer implements ApplicationContextInitializer<ConfigurableApplicationContext> {
I would change this to AbstractIntegrationTest.  Every test would extend this and I would rearrange this to this format
 ```
AbstractIntegrationTest {
 @Container
  public static MariaDBContainer container,,,,

static class DatabaseInitializer implements ApplicationContextInitializer<ConfigurableApplicationContext> {
   public void initalize(....) { ....}
}
}
```

And then ```static { container.start }``` won't be necessary

2023-01-07 09:08 UTC, HerbMat commented on src/test/java/com/dsrm/dsrmbackend/UserControllerIntegrationTests.java
> +    private UserController userController;
unnecessary

2023-01-07 09:08 UTC, HerbMat commented on src/test/java/com/dsrm/dsrmbackend/UserControllerIntegrationTests.java
> +        this.mockMvc = MockMvcBuilders.webAppContextSetup(this.context).build();
I believe if you use ```@AutoConfigureMockMvc``` then it should be done automatically and you can removve this method.

2023-01-07 09:08 UTC, HerbMat commented on src/test/java/com/dsrm/dsrmbackend/UserControllerIntegrationTests.java
> +    @org.junit.jupiter.api.Test
Import this and just use ```**@Test**```

2023-01-09 18:36 UTC, Adrian-Rochminski commented on src/main/java/com/dsrm/dsrmbackend/controllers/UserController.java
> +        return ResponseEntity.of(Optional.of(user.map(userMapper::toUserDTO)));
It seems to me that Optional.of is needed because the method is ultimately supposed to return an optional UserDTO

2023-01-10 00:40 UTC, Adrian-Rochminski commented on src/main/resources/application-local.yml
> +    url: jdbc:mariadb://localhost:3306/TEST
I use a base with a name like this

2023-01-10 17:56 UTC, HerbMat requested changes

2023-01-10 17:56 UTC, HerbMat commented on src/main/java/com/dsrm/dsrmbackend/controllers/UserController.java
> +        if (user.isEmpty()) {
if is not necessarry

2023-01-10 17:56 UTC, HerbMat commented on src/main/java/com/dsrm/dsrmbackend/controllers/UserController.java
> +        return  ResponseEntity.of(Optional.of(user.map(userMapper::toUserDTO)));
```Optional.of``` is not necessarry

2023-01-10 17:56 UTC, HerbMat commented on src/main/resources/application-local.yml
> +    url: jdbc:mariadb://localhost:3306/TEST
yeah. but what about others? Does they also use database with the new name? I believe your database originally should have name as here or not commit this at all. But if everybody wants to change database name in local deployment then ok.

2023-01-10 17:56 UTC, HerbMat commented on src/test/java/com/dsrm/dsrmbackend/AbstractIntegrationTest.java
> +public class AbstractIntegrationTest{
missing abstract keyword

2023-01-11 21:03 UTC, HerbMat requested changes

2023-01-11 21:03 UTC, HerbMat commented on src/test/java/com/dsrm/dsrmbackend/AbstractIntegrationTest.java
> +    public static MariaDBContainer container = new MariaDBContainer<>("mariadb:10")
MariaDBContainer class is generic class so it should be```public static final MariaDBContainer<?> container = ```

2023-01-11 21:03 UTC, HerbMat commented on src/main/java/com/dsrm/dsrmbackend/controllers/UserController.java
> +        return userService.addUser(userRequestDTO);
We should return void and Location header. It was described in task. Here is link how to do that https://shivaprasadgurram.hashnode.dev/how-to-add-location-header-to-spring-mvcs-post-response(It is also in issue)

2023-01-11 21:05 UTC, HerbMat commented on src/test/java/com/dsrm/dsrmbackend/UserControllerIntegrationTests.java
> +        ServletContext servletContext = context.getServletContext();
Unnecessary, Remove. If servletContext fails then none test will start.

2023-01-11 21:09 UTC, HerbMat requested changes

2023-01-11 21:09 UTC, HerbMat commented on src/test/java/com/dsrm/dsrmbackend/UserControllerIntegrationTests.java
> +        this.mockMvc.perform(post("/users")
We missing Location header. To check if exist and has right format

2023-01-11 21:09 UTC, HerbMat commented on src/test/java/com/dsrm/dsrmbackend/UserControllerIntegrationTests.java
> +                .andExpect(jsonPath("$.content[0].name").value("Jan"))
those checks should be more expanded. We should also check second user and more fields

2023-01-11 23:01 UTC, HerbMat requested changes

2023-01-11 23:01 UTC, HerbMat commented on src/test/java/com/dsrm/dsrmbackend/UserControllerIntegrationTests.java
> +                .andExpect(header().stringValues("http://localhost/users/4"));
should be ```.andExpect(header().string("Location", "http://localhost/users/4"))``` because we want that exactly Location header has this value

2023-01-12 21:08 UTC, HerbMat approved these changes

2023-01-12 21:08 UTC, merged