79 move sql inserts
dorm-social-room-manager/dsrm-backend pull request #85
Opened 2023-04-23 15:28 UTC by Krizzuu

closes: #79

2023-04-23 18:56 UTC, Adrian-Rochminski submitted a review, later dismissed
LGTM

2023-04-24 19:18 UTC, HerbMat requested changes

2023-04-24 19:18 UTC, HerbMat commented on README.md
> +There is a file with SQL inserts `data.sql`
I would remove this section. I believe it is not needed. It is more technical input. Our readme should describe only how to run and configure application.

2023-04-24 19:27 UTC, HerbMat commented on src/main/resources/application.properties
> +spring.jpa.defer-datasource-initialization=true
We do not need to put it here. Description in Readme should be enough.

2023-04-25 19:36 UTC, HerbMat approved these changes

2023-04-25 19:37 UTC, merged