81 add new libraries
dorm-social-room-manager/dsrm-backend pull request #88
Opened 2023-05-02 15:01 UTC by Adrian-Rochminski

closes: #81

2023-05-04 13:45 UTC, Krizzuu approved these changes, later dismissed
seems ok

2023-05-04 19:21 UTC, HerbMat requested changes

2023-05-04 19:21 UTC, HerbMat commented on pom.xml
> +            <version>0.8.10</version>
Please move version to properties and use it as variable . It should be done as mapstruct ```mapstruct.version```

2023-05-04 19:21 UTC, HerbMat commented on pom.xml
>              <version>0.11.5</version>
Please fix this as well

2023-05-06 12:11 UTC, HerbMat requested changes

2023-05-06 12:11 UTC, HerbMat commented on pom.xml
>              <version>0.11.5</version>
Still not fixed

2023-05-10 20:48 UTC, HerbMat approved these changes

2023-05-10 20:48 UTC, merged