54 create rest endpoint to update exisitng reservation
dorm-social-room-manager/dsrm-backend pull request #92
Opened 2023-05-17 17:36 UTC by Adrian-Rochminski

closes: #54

2023-05-17 20:18 UTC, Krizzuu commented on src/main/java/com/dsrm/dsrmbackend/services/impl/ReservationServiceImpl.java
> +        Reservation newreservation = reservationMapper.toReservation(reservationRequestDTO);
minor thing: newReservation to match java's naming convention

2023-05-17 20:29 UTC, Krizzuu commented on src/test/java/com/dsrm/dsrmbackend/admin/AdminReservationControllerTests.java
> +    ReservationRepo reservationRepo;
I think it's an unnecessary change

2023-05-17 23:02 UTC, Krizzuu approved these changes, later dismissed
seems ok now

2023-05-17 23:02 UTC, Krizzuu commented on src/test/java/com/dsrm/dsrmbackend/admin/AdminReservationControllerTests.java
> +        Map<String,Object> body = new HashMap<>();
Why you didn't use ReservationRequestDTO?

2023-05-18 21:13 UTC, HerbMat requested changes

2023-05-18 21:13 UTC, HerbMat commented on src/test/java/com/dsrm/dsrmbackend/admin/AdminReservationControllerTests.java
> +        reservationRequestDTO.setFrom(LocalDateTime.parse("2023-05-21T12:20:00"));
WE could extract those dates to variables, instead of creating date from string twice

2023-05-18 21:13 UTC, HerbMat commented on src/test/java/com/dsrm/dsrmbackend/admin/AdminReservationControllerTests.java
> +        reservationRequestDTO.setTo(LocalDateTime.parse("2023-05-22T13:20:00"));
as above

2023-05-22 21:23 UTC, HerbMat approved these changes

2023-05-22 21:23 UTC, merged