52 create endpoint to delete rooms
dorm-social-room-manager/dsrm-backend pull request #93
Opened 2023-05-21 13:32 UTC by Krizzuu

closes: #52

2023-05-22 21:29 UTC, Adrian-Rochminski approved these changes, later dismissed
looks ok

2023-05-23 19:58 UTC, HerbMat requested changes

2023-05-23 19:58 UTC, HerbMat commented on src/main/java/com/dsrm/dsrmbackend/controllers/admin/AdminRoomController.java
> +        Optional<Room> roomType = roomService.deleteRoom(id);
We don't have to check if entity exists. If does not exists then we can also return 204. After all resource does not exists.

2023-05-23 19:58 UTC, HerbMat commented on src/main/java/com/dsrm/dsrmbackend/entities/Room.java
> +    @JsonIgnore
Why json ignore?

2023-05-23 19:58 UTC, HerbMat commented on src/main/java/com/dsrm/dsrmbackend/services/RoomService.java
> +    Optional<Room> deleteRoom(String id);
it should be void as explained above

2023-05-23 19:58 UTC, HerbMat commented on src/main/java/com/dsrm/dsrmbackend/services/impl/RoomServiceImpl.java
> +    public Optional<Room> deleteRoom(String id) {
void as explained above

2023-05-23 19:58 UTC, HerbMat commented on src/test/java/com/dsrm/dsrmbackend/admin/AdminRoomControllerTests.java
> +        this.mockMvc.perform(get("/reservations/1")
I wouldn't perform request to fetch information about reserviations. I would do this via repo. We don't have to test GET endpoint again. And from what I can see there are more reservations which belong to this room.

2023-05-23 19:58 UTC, HerbMat commented on src/test/java/com/dsrm/dsrmbackend/admin/AdminRoomControllerTests.java
> +        this.mockMvc.perform(delete("/admin/rooms/4123")
Unnecessary, because delete should never return not found

2023-05-23 21:03 UTC, HerbMat requested changes

2023-05-23 21:03 UTC, HerbMat commented on src/test/java/com/dsrm/dsrmbackend/admin/AdminRoomControllerTests.java
> +        this.mockMvc.perform(delete("/admin/rooms/4123")
We should also check if room was deleted by using repository method

2023-05-29 08:40 UTC, Adrian-Rochminski requested changes

2023-05-29 08:40 UTC, Adrian-Rochminski commented on src/test/java/com/dsrm/dsrmbackend/admin/AdminRoomControllerTests.java
> +    }
I think this test is unnecessary because such a record doesn't exist anyway so checking if it doesn't exist misses the point

2023-05-29 09:28 UTC, Adrian-Rochminski submitted a review, later dismissed

2023-05-29 19:46 UTC, HerbMat commented on src/main/java/com/dsrm/dsrmbackend/services/impl/RoomServiceImpl.java
> +        Optional<Room> room = roomRepo.findById(id);
Use ```deleteByID```

2023-05-29 19:46 UTC, HerbMat commented on src/test/java/com/dsrm/dsrmbackend/admin/AdminRoomControllerTests.java
> +        assertThat(reservationRepo.findById("1")).isEmpty();
we could use ```reservationRepo.exists```

2023-05-29 19:47 UTC, HerbMat requested changes

2023-05-29 19:47 UTC, HerbMat commented on src/main/java/com/dsrm/dsrmbackend/services/impl/RoomServiceImpl.java
> +        Optional<Room> room = roomRepo.findById(id);
Use ```roomRepo.deleteByID```

2023-05-29 19:48 UTC, HerbMat requested changes
Please fix it

2023-05-31 20:01 UTC, HerbMat approved these changes

2023-05-31 20:01 UTC, merged